[card.kaminari]
id=20000359
ot="custom"
name="Kaminari"
type="trap"
effect='''Target 1 "Hunter X" monster you control; it cannot be destroyed by battle, also, is unaffected by card effects this turn.'''
