[card.godSpeedTransmutator]
id=20000350
ot="custom"
name="Hunter XX - God Speed Transmutator"
set="hunterx"
type="monster fusion effect"
race="thunder"
attribute="dark"
effect='''Must be Special Summoned with "Raging Contract". Your opponent's card effects cannot be activated during the Battle Phase. This card can attack all monsters your opponent controls, once each. If this card would be destroyed by battle or card effect, you can discard 1 "Hunter X" monster from your hand instead.'''
atk=3000
def=2500
level=8
category="repeat_attack destroy_hand"
