# Use this to define local configurations for your project.
# Any configuration defined here will override its global counterpart.
# Global configs are located in `ygo-fabrica/config.toml`,
#  check that file to see possible settings.

[expansion.cards-hxh1]
default = true
recipe = [
  "sets.toml",
  "c20000312.toml",
  "c20000315.toml",
  "c20000319.toml",
  "c20000354.toml",
  "c20000355.toml",
  "c20000356.toml",
  "c20000357.toml",
  "c20000358.toml",
  "c20000359.toml",
  "c20000360.toml",
  "c20000361.toml",
  "c20000370.toml",
  "c20000372.toml",
  "c20000377.toml",
  "c20010370.toml"
]
